# Generated by Django 4.2.5 on 2023-12-09 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_appointment_amount_paid_appointment_refunded_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='icu_status',
            field=models.CharField(choices=[('Admitted', 'Admitted'), ('Critical', 'Critical'), ('Recovered', 'Recovered'), ('Not Needed', 'Not Needed'), ('Discharged', 'Discharged')], default='Not Needed', max_length=20),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='service_charge',
            field=models.PositiveIntegerField(max_length=200),
        ),
    ]
