# Generated by Django 4.2.5 on 2023-12-09 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_appointment_icu_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='service_charge',
            field=models.PositiveIntegerField(),
        ),
    ]
