# Generated by Django 4.2.5 on 2023-12-13 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_doctorprofile_service_charge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=150, max_digits=10),
        ),
    ]
