# Generated by Django 4.2.5 on 2023-12-20 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='doctor_id',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
